In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
%store -r df
df

survived  pclass        age  sibsp  parch     fare  adult_male  alive  \
0           0       3  22.000000      1      0   7.2500           1      0   
1           1       1  38.000000      1      0  71.2833           0      1   
2           1       3  26.000000      0      0   7.9250           0      1   
3           1       1  35.000000      1      0  53.1000           0      1   
4           0       3  35.000000      0      0   8.0500           1      0   
..        ...     ...        ...    ...    ...      ...         ...    ...   
886         0       2  27.000000      0      0  13.0000           1      0   
887         1       1  19.000000      0      0  30.0000           0      1   
888         0       3  29.699118      1      2  23.4500           0      0   
889         1       1  26.000000      0      0  30.0000           1      1   
890         0       3  32.000000      0      0   7.7500           1      0   

     alone  gender  
0        0       1  
1        0       0  
2        1       0  
3        0       0  
4        1       1  
..     ...     ...  
886      1       1  
887      1       0  
888      0       0  
889      1       1  
890      1       1  

[891 rows x 10 columns]

In [3]:
arr=df.to_numpy()
arr

array([[ 0.        ,  3.        , 22.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        ,  1.        , 38.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 1.        ,  3.        , 26.        , ...,  1.        ,
         1.        ,  0.        ],
       ...,
       [ 0.        ,  3.        , 29.69911765, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  1.        , 26.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 0.        ,  3.        , 32.        , ...,  0.        ,
         1.        ,  1.        ]])

In [4]:
np.shape(arr)

(891, 10)

In [5]:
#separate the x and the y axes
# for the x-axis we want columns at index 0 to 10 of the array
X = arr[:,1:10]
X

array([[ 3.        , 22.        ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , 38.        ,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 3.        , 26.        ,  0.        , ...,  1.        ,
         1.        ,  0.        ],
       ...,
       [ 3.        , 29.69911765,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        , 26.        ,  0.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 3.        , 32.        ,  0.        , ...,  0.        ,
         1.        ,  1.        ]])

In [6]:
X.shape

(891, 9)

In [7]:
# for the y-axis, we want columns at index 11 of the array
Y= arr[:,0]
Y.shape

(891,)

In [8]:
# Y=Y.reshape(1,X.shape[1])

In [9]:
XTrain,XTest,YTrain,YTest=train_test_split(X,Y,test_size=0.33,random_state=42)

In [10]:
# XTrain=XTrain.reshape(XTrain.shape[0:])
# print(XTrain.shape)

In [11]:
# XTest=XTest.T
# print(XTest.shape)

In [12]:
# YTrain=YTrain.reshape(-1,1)
# print(YTrain.shape)

In [13]:
# YTest=YTest.reshape(-1,1)
# print(YTest.shape)

In [15]:
model=LogisticRegression(max_iter=10000)
model.fit(XTrain,YTrain)
model.intercept_
model.coef_

array([[-3.50039978e-01, -8.82926415e-03, -2.34962691e-01,
        -1.41888354e-01,  3.34994185e-03, -7.64768638e-01,
         6.83111504e+00, -1.99743419e-01, -5.04683222e-01]])

In [17]:
predict=model.predict(XTest)

In [21]:
# performance
# confusion matrix
pd.DataFrame(confusion_matrix(YTest,predict),columns=['Predicted No','Predicted Yes'],index=['Actual No','Actual Yes'])

Predicted No  Predicted Yes
Actual No            175              0
Actual Yes             0            120

In [23]:
print(classification_report(YTest,predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       175
         1.0       1.00      1.00      1.00       120

    accuracy                           1.00       295
   macro avg       1.00      1.00      1.00       295
weighted avg       1.00      1.00      1.00       295

